### ISSUE TITLE
reset  无效

### ISSUE THREAD

**Issue by bluesky0109** [ltebean/LTNavigationBar#10]
- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    [self.navigationController.navigationBar lt_reset];
}

push to other Controller  navigationBar color can not set to default

**Comment by cy1992s** [comment]
I also have this problem，how do you solve?

**Comment by bluesky0109** [comment]
I Create a view instead of navigationItem and hide navigationbar in viewWillAppear ，and then contorl the color of created  view when scrollview scrolled.

**Comment by mahong125** [comment]
lt_reset有问题，望楼主尽快修复bug

**Comment by ltebean** [comment]
I found the reason, it is because that `scrollViewDidScroll` still gets called after the view disappears, seems it is bug a in iOS 8. So `lt_reset` works fine. You can find the fix in this commit: https://github.com/ltebean/LTNavigationBar/commit/8bec685468586516a2776ad9411ea311e1305a3a
I fixed it by setting the tableView's delegate to nil in `viewWillDisappear`

**Comment by zhangliuliu** [comment]
I have setted the tableView's delegate to nil in viewWillDisappear,but the reset is still not work
